##------------------------------------------------------------------
##------SERVICE CONFIGURATION---------------------------------------
##------------------------------------------------------------------
server:
  port: 8087
spring:
  application:
    name: trading-boot
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
##------------------------------------------------------------------
##------GQL CONFIGURATION-------------------------------------------
##------------------------------------------------------------------
graphql:
  spqr:
    relay:
      connection-check-relaxed: true
    gui:
      enabled: true
      endpoint: /
##------------------------------------------------------------------
##------TRADING ACCOUNT CONFIGURATION-------------------------------
##------------------------------------------------------------------
account:
  position-size-percent: 1
##------------------------------------------------------------------
##------FEATURES CONFIGURATION--------------------------------------
##------------------------------------------------------------------
features:
  paper-trading: true
  screener: finviz
##------------------------------------------------------------------
##------PROVIDERS CONFIGURATION-------------------------------------
##------------------------------------------------------------------
providers:
  webull:
    trade-account:
      id: <redacted>
      pin:
        key: t_token
        secret: <redacted>
    paper-account:
      id: <redacted>
    auth:
      key: access_token
      secret: <redacted>
##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/app.log
    max-size: 10MB
  level:
    com.mg: INFO
    com.mg.trading.boot.domain.rules: INFO
    org.apache.catalina: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.boot: ERROR
management:
  endpoints:
    web.exposure.include: loggers
    loggers.enabled: true

