features:
  paper-trading: true

providers:
  webull:
    trade-account:
      id: 10583124
    paper-account:
      id: 9165031
    auth:
      key: access_token
      secret: dc_us_tech1.183fb203a73-e815c8d646ce455ea7d279ee244eb323

logging:
  level:
    com.mg: INFO
