features:
  paper-trading-enabled: true

providers:
  webull:
    trade-account:
      id: <redacted>
    paper-account:
      id: <redacted>
    auth:
      key: access_token
      secret: <redacted>
