##------------------------------------------------------------------
##------SERVICE CONFIGURATION---------------------------------------
##------------------------------------------------------------------
server:
  port: 8087
spring:
  application:
    name: trading-boot
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
##------------------------------------------------------------------
##------GQL CONFIGURATION-------------------------------------------
##------------------------------------------------------------------
graphql:
  spqr:
    relay:
      connection-check-relaxed: true
    gui:
      enabled: true
      endpoint: /
##------------------------------------------------------------------
##------NLP CONFIGURATION-------------------------------------------
##------------------------------------------------------------------
nlp:
  sentiment:
    annotators: tokenize, cleanxml, ssplit, parse, sentiment
#      annotators: tokenize,cleanxml,ssplit,pos,lemma,ner,parse,depparse,coref,natlog,openie,kbp,entitylink

##------------------------------------------------------------------
##------FEATURES CONFIGURATION--------------------------------------
##------------------------------------------------------------------
features:
  paper-trading: true
  screener: finviz
##------------------------------------------------------------------
##------PROVIDERS CONFIGURATION-------------------------------------
##------------------------------------------------------------------
providers:
  webull:
    trade-account:
      id: <redacted>
    paper-account:
      id: <redacted>
    auth:
      key: <redacted>
      secret: <redacted>
##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/app.log
    max-size: 10MB
  level:
    com.mg: INFO
    com.mg.trading.boot.domain.rules: INFO
    org.apache.catalina: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.boot: ERROR


