#-------------------------------------------
#------CUSTOM PROPERTIES--------------------
#-------------------------------------------
features:
  paper-trading: true
account:
  position-size-percent: 3
providers:
  webull:
    trade-account:
      id: <redacted>
      pin-key: t_token
      pin-secret: <redacted>
    paper-account:
      id: <redacted>
    auth:
      key: access_token
      secret: <redacted>

logging:
  level:
    com.mg: INFO
    com.mg.trading.boot.domain.rules: INFO
