features:
  paper-trading: true
account:
  position-size-percent: 3

providers:
  webull:
    trade-account:
      id: 10583124
      pin:
        key: t_token
        secret: <redacted>
    paper-account:
      id: <redacted>
    auth:
      key: access_token
      secret: <redacted>

logging:
  level:
    com.mg: INFO
    com.mg.trading.boot.domain.rules: INFO
